#readme path
include = ../FreeRTOSv202406.04-LTS/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Kernel/include
all: build

TARGET= binsem_1.out
build: 
	gcc binarysemaphore1.c -I./../FreeRTOSv202406.04-LTS/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Kernel/include -o binarysemaphore.out


	
	



